# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
        types: [file]  # override `types: [json]`
        files: \.(json|sublime-\w*)$
        exclude: \.sublime-workspace
    -   id: pretty-format-json
        args: ["--autofix"]
        types: [file]  # override `types: [json]`
        files: \.(json|sublime-\w*)$
        exclude: \.sublime-workspace
-   repo: https://github.com/perltidy/perltidy
    rev: '20220217.04'
    hooks:
    -   id: perltidy
