from __future__ import annotations


from typing import Optional, Sequence

import json, os

from wraps import AllWraps
from tempfile import NamedTemporaryFile

from textwrap import dedent

import logging


def main(argv: Optional[Sequence[str]] = None) -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=str)
    outputGroup = parser.add_argument_group("Output")
    outputGroup.add_argument("--verbose", "-v", action="count")
    outputGroup.add_argument("--debug", "-d", action="count")
    args = parser.parse_args(argv)
    if args.debug:
        logging.basicConfig(level=logging.DEBUG)
    elif args.verbose:
        logging.basicConfig(level=logging.INFO, format="%(message)s")

    commentWarning = dedent(
        """\
            // This File is automatically generated by the generateKeymap command in
            // the "wrap" python project also contained in this preferences folder.
            //
            // Please do not edit it directly unless for debug purposes.
            //
            // Your changes will be overwritten when the tool is next run.
            //

        """
    )

    logging.info("\n".join([w.name for w in AllWraps]))

    buffer = json.dumps(
        [e for w in AllWraps for e in w.wrap()],
        indent=2,
    )

    with NamedTemporaryFile("w", delete=False) as file:
        file.write(commentWarning + buffer)
        os.replace(file.name, os.path.expanduser(args.output))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
